(source melpa)

(depends-on "auto-complete")
(depends-on "cl-lib-highlight")
(depends-on "grizzl")
(depends-on "highlight-indentation")
(depends-on "multiple-cursors")
(depends-on "pallet")
(depends-on "projectile")
(depends-on "web-mode")
(depends-on "yasnippet")